import {
    ArrowLeft,
    Mail,
    Lock,
    Eye,
    EyeOff,
    AlertCircle,
    Loader2,
    User,
    Phone,
    Menu,
    Clock,
    PenToolIcon,
    Cpu,
    HardDrive,
    Laptop,
    Star,
    Truck,
    CircleArrowDown,
    Moon,
    Sun,
    CheckIcon,
    ChevronRightIcon,
    CircleIcon,
    ChevronDownIcon,
    XIcon,
    LucideProps,
    LogOut,
    UserX,
    MonitorSmartphone,
    CalendarIcon,
    Cookie,
    MoreHorizontal,
} from "lucide-react";

export const Icons = {
    arrowLeft: ArrowLeft,
    mail: Mail,
    lock: Lock,
    eye: Eye,
    eyeOff: EyeOff,
    alertCircle: AlertCircle,
    loader2: Loader2,
    user: User,
    phone: Phone,
    menu: Menu,
    clock: Clock,
    tool: PenToolIcon,
    cpu: Cpu,
    hardDrive: HardDrive,
    laptop: Laptop,
    star: Star,
    truck: Truck,
    circleArrowDown: CircleArrowDown,
    moon: Moon,
    sun: Sun,
    check: CheckIcon,
    chevronRight: ChevronRightIcon,
    circle: CircleIcon,
    chevronDown: ChevronDownIcon,
    x: XIcon,
    logOut: LogOut,
    userX: UserX,
    device: MonitorSmartphone,
    calendar: CalendarIcon,
    cookie: Cookie,
    moreHorizontal: MoreHorizontal,
    logo: ({ ...props }: LucideProps) => {
        <svg {...props}></svg>;
    },
};
